import {
  pgTable,
  text,
  serial,
  integer,
  boolean,
  timestamp,
  pgEnum,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// User role enum
export const userRoleEnum = pgEnum("user_role", [
  "student",
  "admin",
  "superadmin",
]);

// School enum
export const schoolEnum = pgEnum("school", [
  "Ananda Balika Vidyalaya, Colombo",
  "Ananda College, Colombo",
  "Asoka College, Colombo",
  "Devi Balika Vidyalaya, Colombo",
  "D.S. Senanayake College, Colombo",
  "Gothami Balika Vidyalaya, Colombo",
  "Hindu College, Colombo",
  "Isipathana College, Colombo",
  "Mahanama College, Colombo",
  "Muslim Ladies College, Colombo",
  "Nalanda College, Colombo",
  "Ramanathan Hindu Ladies College, Colombo",
  "Rathnawali Balika Maha Vidyalaya, Colombo",
  "Royal College, Colombo",
  "Sirimavo Bandaranaike Balika Vidyalaya, Colombo",
  "St Paul’s Girls School, Colombo",
  "Thurston College, Colombo",
  "Visakha Vidyalaya, Colombo",
  "Lumbini College, Colombo",
  "Mahinda Rajapaksha Vidyalaya, Homagama",
  "Rathnavali Balika MV, Gampaha",
  "Bandaranayaka Vidyalaya, Gampaha",
  "Vihara Maha Devi Balika Vidyalaya, Kiribathgoda",
  "Anula Vidyalaya, Nugegoda",
  "Dharmapala Vidyalaya, Pannipitiya",
  "Bandaranayake Central College, Veyangoda",
  "Prince of Wales’ College, Moratuwa",
  "Sri Dharmaloka Collage",
  "Yashodara Devi Balika Maha Vidyalaya - Gampaha",
  "Kotahena Central College",
  "Sri Sangabodhi National College",
  "Thakshila College Gampaha",
  "President's College",
  "Andiambalama Maha Vidyalaya",
  "SRI Subhuthi National school",
  "Harischandra College",
  "Boys' Model College, Malabe",
  "Hameed Al Husseinie College",
  "Kelani Maha Vidyalaya",
  "Ananda Sastralaya, Kotte",
  "Siyane National School",
  "St. Paul's Balika Maha Vidyalaya, Kelaniya",
  "Galahitiyawa Central College, Ganemulla",
  "Newstead Girls College, Negombo",
  "Gurukula College, Kelaniya",
  "Nalanda (Boys') Central College, Minuwangoda",
  "D.S. Senanayake Central College, Mirigama",
  "Henegama Central College - National School, Henegama",
  "St. Anthony's College, Wattala",
  "Nalanda (Girls') Central College, Minuwangoda",
  "President's College, Minuwangoda",
  "Bomiriya Central College, Bomiriya, Kaduwela.",
  "SRI RAJASINGHE CENTRAL, MULLERIYAWA",
  "Kolonnawa Girl's College",
  "Hanwella Rajasinghe Central College",
  "Seethawaka National School",
  "Piliyandala Central College",
  "Presbyterian Girls' School Dehiwala",
  "Central College Homagama",
  "Princess of Wales' College",
  "Science College, Mount Lavinia",
  "Lalith Athulathmudali College, Mount Lavinia",
  "Sri Pangnananda Vidyalaya, Kotugoda",
  "Christ King College, Tudella",
  "Al-Mubarak Central College, Malwana",
  "Senarath Paranawithana Maha Vidyalaya, Udugampola",
  "Sri Chandrajothi Maha Vidyalaya, Yakkala",
  "Anura Madhya Maha Vidyalaya, Yakkala",
  "Madduma Bandara Maha Vidyalaya, Weliweriya",
  "Rajasinghe Maha Vidyala, Imbulgoda",
  "Al Ashar Muslim Maha Vidyalaya, Thihariya",
  "President's College, Veyangoda",
  "Urapola Madhya Maha Vidyalaya, Urapola",
  "Kirindiwela Madhya Maha Vidyalaya, Kirindiwela",
  "Padmawathie Madhya Maha Vidyalaya, Dekatan",
  "St Peter’s College, Negombo",
  "Al Hilal Muslim Central College, Negombo",
  "Wijayaratnam Hindu Central College, Negombo",
  "St. Mary’s College, Negombo",
  "Kochchikade Maha Vidyalaya, Kochchikade",
  "Nirmala Mariya Balika Maha Vidyalaya, Ja Ela",
  "St. Sebastian's Balika Maha Vidyalaya, Kandana",
  "St. Sebastian’s College, Kandana",
  "Basilica College, Ragama",
  "Batuwatta Maha Vidyalaya, Ragama",
  "Jinaraja Maha Vidyalaya, Ja Ela",
  "Dutugamunu Maha Vidyalaya, Thimbirigaskotuwa",
  "Davi Samara Maha Vidyalaya, Seeduwa",
  "Deshamanya H.K Dharamadasa Maha Vidyalaya, Peliyagoda",
  "Good Sheperd Balika Maha Vidyalaya, Wattala",
  "St. Anne's Balika Maha Vidyalaya, Wattala",
  "Heenkenda Maha Vidyalaya, Ragama",
  "Vishaka Balika Maha Vidyalaya, Makola",
  "Sapugaskanda Maha Vidyalaya, Makola",
  "Mahamaya Balika Maha Vidyalaya, Kadawatha",
  "Biyagama Madhya Maha Vidyalaya, Biyagama",
  "Daranagama Maha Vidyalaya, Siyambalape",
  "Kadawatha Madhya Maha Vidyalaya, Kadawatha",
  "S.K.K Sooriyaarachchi Maha Vidyalaya, Kadawatha",
  "Kirillawala Madhya Maha vidyalaya, Kadawatha",
  "Burullapitiya Maha Vidyalaya, Minuwangoda",
  "Dewalapola Ananda Maha Vidyalaya, Dewalapola",
  "Pallewela Maha Vidyalaya, Pallewela",
  "Pasyala Maha Vidyalya, Pasyala",
  "C.W.W Kannangara Maha Vidyalaya, Hunumulla",
  "Sri Gnanodaya Madhya Maha Vidyalaya, Divulapitiya",
  "Kalutara Vidyalaya",
  "Kalutara Balika Vidyalaya, Kalutara",
  "Tissa Central College, Kalutara",
  "Zahira College, Dharga Town",
  "Saddhathissa College, Bandaragama",
  "D.S Senanayake Central College, Beruwala",
  "Al-Humaisara National School, Beruwala",
  "Sri Sumangala College, Panadura",
  "St. John's College, Panadura",
  "Sri Sumangala Girls College, Pandura",
  "Miriswatta National School, Dodangoda",
  "Horana Royal College, Horana",
  "Taxila Central College, Horana",
  "Sri Palee College, Horana",
  "Bandaragama National School, Bandaragama",
  "Bulathsinhala Central College, Bulathsinhala",
  "Ananda Sastralaya, Matugama",
  "C. W. W. Kannangara Madya Maha Vidyalaya, Mathugama",
  "Panadura Royal College",
  "Agamathi Balika Vidyalaya Panadura",
  "Gnanodaya Maha Vidyalaya, Kalutara South",
  "Gurulugomi Maha Vidyalaya, Kalutara North",
  "Muslim Central College, Kalutara South",
  "Katukurunda Dharmapala Maha Vidyalaya, Katukurunda",
  "Al Faharia Muslim Central College, Pandura",
  "Jeelan Central College, Pandura",
  "Mahanama College, Pandura",
  "Pandura Balika Maha Vidyalaya, Pandura",
  "Wadduwa Madhya Maha Vidyalaya, Wadduwa",
  "Sri Gnanissara Maha Vidyalaya, Dharga Town",
  "Naleem Hajiar Muslim Balika Vidyalaya, Beruwala",
  "Zam Refai Hajiar Maha Vidyalaya, Beruwala",
  "Pothuwila Maha Vidyalaya, Payagala",
  "Zahira Muslim Maha Vidyalaya, Dharga Town",
  "Bombuwala Sri Dharmaloka Maha Vidyalaya, Bombuwala",
  "Don Pedrick Maha Vidyalaya, Horana",
  "Prajapathi Balia Maha Vidyalaya, Horana",
  "Sri Medhankara Maha Vidyalaya, Horana",
  "Gamini Madhya Maha Vidyalaya, Ingiriya",
  "Palannoruwa Central College, Gonapola Junction",
  "Sri Saddhatissa Maha Vidyalaya, Bandaragama",
  "Wewita Maithree Maha Vidyalaya, Bandaragama",
  "Warakagoda Maha Vidyalaya, Neboda",
  "St. Mary's College, Matugama",
  "Walagedara Maha Vidyalaya, Walagedara",
  "Mihindu Madhya Maha Vidyalaya, Agalawatta",
  "Kamburawala Maha Vidyalaya, Baduraliya",
  "Colvin R. De Silva maha Vidyalaya, Ittapana",
  "Meril Kariyawasam Madhya Maha Vidyalaya, Meeghatenna",
  "Bishop's College, Colombo",
  "Burhani Serandib School, Colombo",
  "Buddhist Ladies' College, Colombo",
  "Carey College, Colombo",
  "Ladies' College, Colombo",
  "Convent of Our lady of Victories, Moratuwa",
  "Elizabeth Moir School, Colombo",
  "Good Shepherd Convent, Colombo",
  "Gateway College Dehiwala",
  "Gateway College Colombo",
  "Hindu Ladies College, Colombo",
  "Holy Family Convent, Bambalapitiya",
  "Holy Family Convent, Dehiwela",
  "Kanza College, Colombo",
  "Kebel College, Nugegoda",
  "Logos College, Colombo",
  "Louvre College, Pannipitiya",
  "Louvre College, Nugegoda",
  "Methodist College, Colombo",
  "Musaeus College, Colombo",
  "NCEF Buddhist College, Mulleriyawa",
  "Spectrum College, Mount Lavinia",
  "St. Lawrence's Convent, Colombo",
  "St. Benedict's College, Colombo",
  "Minasro College, Pelawatta, Mathugama",
  "St. Peter's College, Colombo",
  "St. Sebastian's College, Moratuwa",
  "St. Bridget's Convent, Colombo",
  "St. Thomas' College, Mount Lavinia",
  "Sujatha Vidyalaya, Nugegoda",
  "St. Joseph's Boys’ College, Nugegoda",
  "Sussex College, Nugegoda",
  "Springfield College, Colombo",
  "Highlands College, Maharagama",
  "Vidura College, Nawala",
  "Wesley College, Colombo",
  "Al Manar International School, Colombo",
  "Alexor International School, Colombo",
  "Amal International School, Colombo",
  "Apple International School, Colombo",
  "Asian International School, Colombo",
  "ACE Institute International School, Colombo",
  "Belvoir College International, Colombo",
  "Bond International School, Colombo",
  "Brightens International School, Colombo",
  "Buckingham International School, Colombo",
  "Brisbane International School, Nugegoda",
  "British School in Colombo",
  "Cambridge International School, Colombo",
  "Campbell International School, Colombo",
  "Campbell International School, Kotikawatta",
  "Colombo International School, Colombo",
  "Crescent Schools International, Colombo",
  "Crescent Schools International, Wellampitiya",
  "Colombo South International College, Nugegoda",
  "Dhilshaath International College, Dematagoda",
  "East Asian International College, Nugegoda",
  "Eskola International School, Colombo",
  "Global International School, Colombo",
  "Green Bridge International College, Kolonnawa",
  "Guidance International School, Piliyandala",
  "Harcourts International School, Dehiwala",
  "Hejaaz International School, Mount Lavinia",
  "Horizon College International, Malabe",
  "Horizon College International, Nugegoda",
  "Hilburn International School, Avissawella",
  "Ikra International School, Colombo",
  "Ikra International School, Kolonnawa",
  "Ilma International Girls' School, Colombo",
  "J.M.C. International School, Colombo",
  "J.M.C. International School, Kaduwela",
  "J.M.C. International School, Maharagama",
  "J.M.C. International School, Mulleriyawa",
  "Kingston College International, Wellawatta",
  "Kingston College International, Colombo",
  "Kingston College International, Mount Lavinia",
  "Lakeland International American School, Ratmalana",
  "Lead the Way Girls' International, Dehiwala",
  "Leeds International School, Piliyandala",
  "Liberty International School, Colombo",
  "Liberty International School, Ethul Kotte",
  "Lyceum International School, Nugegoda",
  "Linfield International School, Mortuwa",
  "Linfield International School, Piliyandala",
  "Linfield International School, Pannipitiya",
  "Linfield International School, Godagama",
  "M.D Gunasena International School, Colombo",
  "Mysticle Rose Institute International School, Ethulotte",
  "Readway International College of Education, Dematagoda",
  "Royal Institute International School, Nugegoda",
  "Royal Institute International School, Colombo",
  "Royal Institute International School, Maharagama",
  "School of Arts and Science, Colombo",
  "Stafford International School, Colombo",
  "Wycherley International School, Colombo",
  "Other",
]);

// User table schema
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
  role: userRoleEnum("role").notNull().default("student"),
  school: schoolEnum("school"),
  lastLogin: timestamp("last_login"),
  createdAt: timestamp("created_at").defaultNow(),
});

// Questions table schema
export const questions = pgTable("questions", {
  id: serial("id").primaryKey(),
  questionText: text("question_text").notNull(),
  optionA: text("option_a").notNull(),
  optionB: text("option_b").notNull(),
  optionC: text("option_c").notNull(),
  optionD: text("option_d").notNull(),
  correctAnswer: text("correct_answer").notNull(),
  difficulty: text("difficulty").default("medium"),
  createdBy: integer("created_by").references(() => users.id),
  createdAt: timestamp("created_at").defaultNow(),
});

// Quiz state enum
export const quizStateEnum = pgEnum("quiz_state", [
  "waiting",
  "started",
  "completed",
]);

// Quiz settings table schema
export const quizSettings = pgTable("quiz_settings", {
  id: serial("id").primaryKey(),
  state: quizStateEnum("state").notNull().default("waiting"),
  startTime: timestamp("start_time"),
  endTime: timestamp("end_time"),
  lastReset: timestamp("last_reset"),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// Quiz answers table schema
export const quizAnswers = pgTable("quiz_answers", {
  id: serial("id").primaryKey(),
  userId: integer("user_id")
    .notNull()
    .references(() => users.id),
  questionId: integer("question_id")
    .notNull()
    .references(() => questions.id),
  userAnswer: text("user_answer"),
  isCorrect: boolean("is_correct"),
  responseTimeSeconds: integer("response_time_seconds"),
  createdAt: timestamp("created_at").defaultNow(),
});

// Results table schema
export const results = pgTable("results", {
  id: serial("id").primaryKey(),
  userId: integer("user_id")
    .notNull()
    .references(() => users.id),
  score: integer("score").notNull(),
  correctAnswers: integer("correct_answers").notNull(),
  incorrectAnswers: integer("incorrect_answers").notNull(),
  skippedAnswers: integer("skipped_answers").notNull(),
  averageResponseTime: integer("average_response_time"),
  completionTime: integer("completion_time"),
  rank: integer("rank"),
  createdAt: timestamp("created_at").defaultNow(),
});

// Zod schemas for form validation
export const insertUserSchema = createInsertSchema(users).omit({
  id: true,
  lastLogin: true,
  createdAt: true,
});

export const insertQuestionSchema = createInsertSchema(questions).omit({
  id: true,
  createdAt: true,
});

export const insertQuizSettingsSchema = createInsertSchema(quizSettings).omit({
  id: true,
  startTime: true,
  endTime: true,
  lastReset: true,
  updatedAt: true,
});

export const insertQuizAnswerSchema = createInsertSchema(quizAnswers).omit({
  id: true,
  isCorrect: true,
  createdAt: true,
});

export const insertResultSchema = createInsertSchema(results).omit({
  id: true,
  createdAt: true,
});

export const loginSchema = z.object({
  username: z.string().min(3, "Username is required"),
  password: z.string().min(1, "Password is required"),
  school: z.string().optional(),
  role: z.enum(["student", "admin", "superadmin"]).optional(),
});

// Types
export type User = typeof users.$inferSelect;
export type InsertUser = z.infer<typeof insertUserSchema>;
export type Question = typeof questions.$inferSelect;
export type InsertQuestion = z.infer<typeof insertQuestionSchema>;
export type QuizSetting = typeof quizSettings.$inferSelect;
export type InsertQuizSetting = z.infer<typeof insertQuizSettingsSchema>;
export type QuizAnswer = typeof quizAnswers.$inferSelect;
export type InsertQuizAnswer = z.infer<typeof insertQuizAnswerSchema>;
export type Result = typeof results.$inferSelect;
export type InsertResult = z.infer<typeof insertResultSchema>;
export type LoginCredentials = z.infer<typeof loginSchema>;
